version: '3'

services:
  appdemo:
    build:
      context: .
      dockerfile: ./docker/development.Dockerfile
    env_file: docker/.env
    container_name: app_developtment
    links:
      - mongo
    ports:
      - "3000:3000"
    # mount source volume, but
    # don't overwrite `node_modules` or mirror dir from container
    volumes:
      - ${PWD}:/usr/src
      - /usr/src/node_modules
    tty: true

  mongo:
    image: mongo:3.2
    container_name: mongo_developtment
    volumes:
      - ./tmp/db:/data/db
