version: '3'

services:
  app:
    container_name: democracyos_developtment
    command: ["./node_modules/.bin/gulp", "bws"]
    environment:
      - NODE_ENV=development
      - DEBUG=democracyos*
      - MONGO_URL=mongodb://mongo/development
    links:
      - mongo
    ports:
      - 3000:3000
    volumes:
      - ./ext/lib:/usr/src/ext/lib
      - ./public:/usr/src/public
    tty: true

  mongo:
    container_name: mongo_developtment
    volumes:
      - ./tmp/db:/data/db
