version: '3'
services:
  appdemo:
    build:
      context: .
    environment:
      - NODE_ENV='production'
    links:
      - mongo
    ports:
      - "3000:3000"
    # mount source volume, but
    # don't overwrite `node_modules` or mirror dir from container
    volumes:
      - ${PWD}:/usr/src
      - /usr/src/node_modules
    tty: true
    restart: unless-stopped
    


  mongo:
    image: mongo:3.2
    container_name: MongoProduction
    volumes:
      - ./tmp/db:/data/db
    restart: unless-stopped


  nginx:
    build:
      context: ./nginx
    container_name: "NginxProduction"
    links:
      - appdemo 
    ports:
      - "80:80"
    depends_on:
      - appdemo
    volumes:
      - .:/www/data/democracy/app
   #   - /nginx/logs/log_error:/var/log/nginx/
    restart: unless-stopped


