version: '3'
services:
  appdemo:
    build:
      context: .
    environment:
      - NODE_ENV='production'
    env_file: docker/.env
    links:
      - mongo
    ports:
      - "3000:3000"
    # mount source volume, but
    # don't overwrite `node_modules` or mirror dir from container
    volumes:
      - ${PWD}:/usr/src
      - /usr/src/node_modules
    tty: true
    restart: unless-stopped
    networks:
      app_net:
        ipv4_address: '$IP_NODE'


  mongo:
    image: mongo:3.2
    container_name: MongoProduction
    volumes:
      - ./tmp/db:/data/db
    networks:
      app_net:
        ipv4_address: '$IP_MONGO'
    restart: unless-stopped


  nginx:
    build:
      context: ./nginx
    container_name: "NginxProduction"
    env_file: .env
    links:
      - appdemo 
    ports:
      - "80:80"
    depends_on:
      - appdemo
    volumes:
      - .:/www/data/democracy/app
    networks:
      app_net:
        ipv4_address: '$IP_NGINX'
    #   - /nginx/logs/log_error:/var/log/nginx/
    restart: unless-stopped

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.1.0/24  
