version: '3'

services:
  app:
    container_name: DemocracyosProduction
    command: ["./node_modules/.bin/gulp", "bws"]
    environment:
      - NODE_ENV=development
      - DEBUG=democracyos*
      - MONGO_URL=mongodb://mongo/production
    links:
      - mongo
    ports:
      - 3000:3000
    volumes:
      - ./ext/lib:/usr/src/ext/lib
      - ./public:/usr/src/public
    tty: true
    restart: unless-stopped
    networks:
      app_net:
        ipv4_address: '$IP_NODE'


  mongo:
    container_name: MongoProduction
    volumes:
      - ./tmp/db:/data/db
    networks:
      app_net:
        ipv4_address: '$IP_MONGO'
    restart: unless-stopped


  nginx:
    build:
      context: ./nginx
    container_name: "NginxProduction"
    env_file: .env
    links:
      - app   
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - .:/www/data/democracy/app
    networks:
      app_net:
        ipv4_address: '$IP_NGINX'
    #   - /nginx/logs/log_error:/var/log/nginx/
    restart: unless-stopped

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.1.0/24  
